[project]
name = "rkitpy"
version = "0.1"
description = "My Python library"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE.txt"]
keywords = ["pandas", "polars", "data science", "data wrangling"]
authors = [
    { name = "Raffaele Mancuso", email = "raffaelemancuso532@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.15.0",
    "jsonpickle>=4.1.2",
    "natsort>=8.4.0",
    "python-docx>=1.2.0",
    "rich>=14.2.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
pandas = [
	"pandas>=2.3.3",
]
polars = [
	"polars>=1.38.1",
	"polars-config-meta>=0.3.1",
	"polars-permute>=0.1.6",
]
bibliometrics = [
    "fake-useragent>=2.2.0",
]
db = [
    "sqlalchemy>=2.0.48",
]
rnote = [
    "pillow>=12.0.0",
    "pymupdf>=1.26.0",
]
dev = [
    "ruff>=0.15.5",
    "pytest>=8.4.0",
]
docs = [
    "sphinx>=9.1.0",
    "sphinx-autoapi>=3.8.0",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-rtd-theme>=3.1.0",
]
web = [
    "selenium>=4.41.0",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"